#!/usr/bin/env bash

set -e # stop script on error
#set -x # print commands

USAGE="usage: $(basename "$0") add|remove IP[:PORT]"

if [[ "$1" !=  "add" ]] && [[ "$1" !=  "remove" ]] || [ $# != 2 ]; then
  echo $USAGE
  exit 1
fi

INSTANCE=$2
UPSTREAM_CONFIG_FILE=/etc/nginx/conf.d/nginx_upstream.conf

if [[ "$1" ==  "add" ]]; then
  if grep -q "$INSTANCE;" $UPSTREAM_CONFIG_FILE; then
    echo "instance already present"
    exit 0
  else
    head -n -1 $UPSTREAM_CONFIG_FILE | grep -v "$INSTANCE;" > temp.txt
    echo "    server $INSTANCE;" >> temp.txt
    echo "}" >> temp.txt
    mv temp.txt $UPSTREAM_CONFIG_FILE
    service nginx restart
    echo "instance added to load balancer"
    exit 0
  fi
fi

if [[ "$1" ==  "remove" ]]; then
  if grep -q "$INSTANCE;" $UPSTREAM_CONFIG_FILE; then
    grep -v "$INSTANCE;" $UPSTREAM_CONFIG_FILE > temp.txt
    mv temp.txt $UPSTREAM_CONFIG_FILE
    service nginx restart
    echo "instance removed from load balancer"
    exit 0
  else
    echo "instance not found"
    exit 0
  fi
fi
